export { default as InformationIndication } from './InformationIndication'
export { default as PaintingListInfinite } from './PaintingListInfinite'
export { default as PaintingCard } from './PaintingCard'
export { default as Footer } from './Footer'
export { default as Tag } from './Tag'
export { default as NavMenu } from './NavMenu'